# Generated by Django 3.2.11 on 2022-05-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('6 Month', '6month'), ('12 Month', '12month'), ('1 Month(Free)', 'free')], default='1 Month(Free)', max_length=50),
        ),
    ]
