# Generated by Django 3.2.11 on 2022-07-05 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20220612_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='date_of_membership',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
