# Generated by Django 3.2.11 on 2022-07-12 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20220705_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='description',
            field=models.TextField(default='aaa'),
        ),
        migrations.AddField(
            model_name='membership',
            name='image',
            field=models.ImageField(default='image', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='membership',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='membership', to='membership.membership'),
        ),
    ]
