# Generated by Django 3.2.11 on 2022-07-24 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0016_assets_price'),
        ('paper_trading', '0002_alter_papertrading_closed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papertrading',
            name='average_price',
        ),
        migrations.RemoveField(
            model_name='papertrading',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='papertrading',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='papertrading',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='papertrading',
            name='side',
        ),
        migrations.RemoveField(
            model_name='papertrading',
            name='status',
        ),
        migrations.RemoveField(
            model_name='papertrading',
            name='assets',
        ),
        migrations.AddField(
            model_name='papertrading',
            name='assets',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paper_trading', to='market.assets'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='papertrading',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PropertyPaperTrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_price', models.FloatField()),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('status', models.CharField(choices=[('OPENED', 'opened'), ('CLOSED', 'closed')], default='opened', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('side', models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell')], max_length=4)),
                ('assets', models.ManyToManyField(related_name='property_trading', to='market.Assets')),
            ],
        ),
        migrations.AddField(
            model_name='papertrading',
            name='property_paper_trading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paper_trading.propertypapertrading'),
        ),
    ]
