# Generated by Django 3.2.11 on 2022-07-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0007_auto_20220725_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papertrading',
            name='assets',
        ),
    ]
