# Generated by Django 3.2.11 on 2022-07-26 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_assets_price'),
        ('paper_trading', '0008_remove_papertrading_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papertrading',
            name='property_paper_trading',
        ),
        migrations.AddField(
            model_name='papertrading',
            name='assets',
            field=models.ManyToManyField(through='paper_trading.PropertyPaperTrading', to='market.Assets'),
        ),
        migrations.AddField(
            model_name='propertypapertrading',
            name='paper_trading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paper_trading.papertrading'),
        ),
        migrations.RemoveField(
            model_name='propertypapertrading',
            name='assets',
        ),
        migrations.AddField(
            model_name='propertypapertrading',
            name='assets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.assets'),
        ),
    ]
