# Generated by Django 3.2.11 on 2022-07-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0009_auto_20220726_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypapertrading',
            name='average_price',
            field=models.FloatField(null=True),
        ),
    ]
