# Generated by Django 3.2.11 on 2022-03-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_portfolio_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='investor',
            new_name='user',
        ),
    ]
