# Generated by Django 3.2.11 on 2022-03-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_rename_investor_portfolio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='market',
        ),
    ]
