# Generated by Django 3.2.11 on 2022-04-12 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_market_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='portfolio',
        ),
    ]
