# Generated by Django 3.2.11 on 2022-04-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_remove_market_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='assets',
            field=models.ManyToManyField(related_name='market_assets', to='market.Assets'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='assets',
            field=models.ManyToManyField(related_name='portfolio_assets', to='market.Assets'),
        ),
    ]
