# Generated by Django 3.2.11 on 2022-04-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20220416_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='assets',
            name='price',
            field=models.FloatField(),
        ),
    ]
