# Generated by Django 3.2.11 on 2022-05-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20220417_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='core_key',
            field=models.CharField(default='usdt', max_length=10),
        ),
        migrations.AddField(
            model_name='assets',
            name='image',
            field=models.ImageField(default='image', upload_to=''),
        ),
    ]
