# Generated by Django 3.2.11 on 2022-05-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20220508_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='image',
            field=models.ImageField(default='image', upload_to='media'),
        ),
    ]
