# Generated by Django 3.2.11 on 2022-06-28 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_alter_assets_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='price',
        ),
    ]
