# Generated by Django 3.2.11 on 2022-07-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_assets_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
