# Generated by Django 3.2.11 on 2022-03-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_portfolio_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
