# Generated by Django 3.2.11 on 2022-05-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_adviser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adviser',
        ),
        migrations.AddField(
            model_name='user',
            name='is_adviser',
            field=models.BooleanField(default=False),
        ),
    ]
