# Generated by Django 3.2.11 on 2022-05-15 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_auto_20220515_0919'),
        ('accounts', '0013_auto_20220515_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.courses'),
        ),
    ]
