# Generated by Django 3.2.11 on 2022-05-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_auto_20220515_0919'),
        ('accounts', '0014_user_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(null=True, related_name='user_courses', to='academy.Courses'),
        ),
    ]
