# Generated by Django 3.2.11 on 2022-05-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_auto_20220515_0919'),
        ('accounts', '0015_auto_20220515_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='academy.Courses'),
        ),
    ]
