# Generated by Django 3.2.11 on 2022-06-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_alter_advicerequests_advice_requests'),
        ('accounts', '0016_alter_user_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='user_courses', to='academy.Courses'),
        ),
    ]
