# Generated by Django 3.2.11 on 2022-04-19 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0012_auto_20220417_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('time_frame', models.CharField(max_length=10)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='market', to='market.market')),
            ],
        ),
    ]
