# Generated by Django 3.2.11 on 2022-04-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20220417_1046'),
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterAssets',
            new_name='RegisterSymbol',
        ),
    ]
