# Generated by Django 3.2.11 on 2022-04-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0002_rename_registerassets_registersymbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registersymbol',
            name='time_frame',
            field=models.CharField(choices=[('1day', 'One Day'), ('4hours', 'Four Hours')], default='4hours', max_length=10),
        ),
    ]
