# Generated by Django 3.2.11 on 2022-04-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0003_alter_registersymbol_time_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registersymbol',
            name='symbol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
