# Generated by Django 3.2.11 on 2022-04-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0004_alter_registersymbol_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registersymbol',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
    ]
