# Generated by Django 3.2.11 on 2022-05-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0005_alter_registersymbol_symbol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterSymbol',
        ),
    ]
