# Generated by Django 3.2.11 on 2022-05-15 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0004_remove_courses_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
