# Generated by Django 3.2.11 on 2022-05-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_courses_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='user',
        ),
    ]
