# Generated by Django 3.2.11 on 2022-05-21 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0006_auto_20220515_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='advicerequests',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_advice_requests', to='accounts.user'),
            preserve_default=False,
        ),
    ]
