# Generated by Django 3.2.11 on 2022-05-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_auto_20220528_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advicerequests',
            name='advice_requests',
            field=models.CharField(choices=[('Yes', 1), ('No', 0)], default='YES', max_length=10),
        ),
    ]
