# Generated by Django 3.2.11 on 2022-05-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_alter_advicerequests_advice_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advicerequests',
            name='advice_requests',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='YES', max_length=10),
        ),
    ]
