# Generated by Django 3.2.11 on 2022-06-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_courses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='advicerequests',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
