# Generated by Django 3.2.11 on 2022-06-14 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0012_advicerequests_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCoursesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='academy.courses')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='exams',
            name='course',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='exam',
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.DeleteModel(
            name='Exams',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
