# Generated by Django 3.2.11 on 2022-07-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_auto_20220712_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AlterUniqueTogether(
            name='exams',
            unique_together={('course', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together={('exam', 'position')},
        ),
    ]
