# Generated by Django 3.2.11 on 2022-07-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_auto_20220717_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.TextField(verbose_name='https://heepnow.arvanvod.com/bl4v5dXOWJ/Mz51Xr0EYx'
                                                '/origin_KrCCiqJrEAIpUFHijkD05HkRM3z5zzG9mzwwXgTp.mp4'),
        ),
    ]
