# Generated by Django 3.2.11 on 2022-07-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0018_auto_20220723_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctanswer',
            name='answer',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=10),
        ),
        migrations.AlterField(
            model_name='responseexam',
            name='answer',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=10),
        ),
    ]
