# Generated by Django 3.2.11 on 2022-07-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_auto_20220724_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctanswer',
            name='answer',
            field=models.CharField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], max_length=10),
        ),
        migrations.AlterField(
            model_name='responseexam',
            name='answer',
            field=models.CharField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], max_length=10),
        ),
    ]
