# Generated by Django 3.2.11 on 2022-07-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0021_auto_20220725_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctanswer',
            name='answer',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
        migrations.AlterField(
            model_name='responseexam',
            name='answer',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
