# Generated by Django 3.2.11 on 2022-08-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0022_auto_20220725_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_file',
            new_name='video_field',
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_a',
            field=models.TextField(default='a', max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_b',
            field=models.TextField(default='b', max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_c',
            field=models.TextField(default='c', max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_d',
            field=models.TextField(default='d', max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(max_length=2500),
        ),
    ]
