# Generated by Django 3.2.11 on 2022-08-14 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0024_auto_20220814_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='mycourseslist',
            name='teacher',
        ),
    ]
