# Generated by Django 3.2.11 on 2022-09-03 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0026_auto_20220814_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourseslist',
            name='courses',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_courses', to='academy.courses'),
        ),
    ]
